# Generated by Django 2.0.6 on 2018-09-14 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('upload', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=45)),
                ('ip', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10)),
                ('temp', models.CharField(max_length=10)),
                ('humidity', models.CharField(max_length=10)),
                ('power', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('devID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Devices')),
            ],
        ),
        migrations.CreateModel(
            name='Network_devices',
            fields=[
                ('ser_num', models.IntegerField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('ser_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Network_devices')),
                ('status', models.CharField(max_length=10)),
                ('manufacturer', models.CharField(max_length=25)),
                ('up_time', models.CharField(max_length=25)),
                ('interface_using', models.CharField(max_length=255)),
                ('sw_image', models.CharField(max_length=25)),
                ('sw_version', models.CharField(max_length=25)),
                ('last_reset', models.CharField(max_length=15)),
                ('fan', models.CharField(max_length=5)),
                ('temp', models.CharField(max_length=5)),
                ('power', models.CharField(max_length=5)),
                ('ip', models.CharField(max_length=15)),
                ('serial_port', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='network_devices',
            name='con_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Controller'),
        ),
        migrations.AddField(
            model_name='network_devices',
            name='devID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Devices'),
        ),
        migrations.AddField(
            model_name='network_devices',
            name='modID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Model'),
        ),
        migrations.AddField(
            model_name='management',
            name='ser_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Network_devices'),
        ),
        migrations.AddField(
            model_name='management',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
        migrations.AddField(
            model_name='base_template',
            name='modID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Model'),
        ),
    ]
