# Generated by Django 2.0.6 on 2018-09-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='status',
        ),
    ]
