# Generated by Django 2.0.6 on 2018-09-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_controller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
