# Generated by Django 2.0.6 on 2018-09-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_controller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='hostname',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='controller',
            name='ip',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='network_devices',
            name='hostname',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
