# Generated by Django 2.0.6 on 2018-09-15 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180915_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='ser_num',
            field=models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.Network_devices'),
        ),
        migrations.AlterField(
            model_name='network_devices',
            name='ser_num',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
