# Generated by Django 2.0.6 on 2018-10-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181004_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_template',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
