# Generated by Django 2.0.6 on 2018-10-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_base_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='humidity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='controller',
            name='temp',
            field=models.CharField(max_length=100),
        ),
    ]
