# Generated by Django 2.0.6 on 2018-10-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20181024_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='ip',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
