# Generated by Django 2.0.6 on 2018-10-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20181024_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='humidity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='controller',
            name='power',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='controller',
            name='temp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
