# Generated by Django 2.0.6 on 2018-10-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20181024_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controller',
            old_name='humidity',
            new_name='sensor1',
        ),
        migrations.RenameField(
            model_name='controller',
            old_name='temp',
            new_name='sensor2',
        ),
        migrations.AddField(
            model_name='controller',
            name='sensor3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='controller',
            name='sensor4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
