# Generated by Django 2.0.6 on 2018-10-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20181025_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='last_reset',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='detail',
            name='manufacturer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='detail',
            name='sw_image',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='sw_version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='up_time',
            field=models.CharField(max_length=255),
        ),
    ]
