# Generated by Django 2.0.6 on 2018-11-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20181111_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='old_config',
        ),
    ]
